spring:
  datasource:
    url: jdbc:mariadb://192.168.10.45:3306/task_service?useSSL=false
    username: developer
    password: '%$developer321'
    # driverClassName: org.mariadb.jdbc.Driver 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MariaDB106Dialect

  cloud:
    config:
      allow-override: true
      override-system-properties: false

server:
  port: 8083

time-zone: GMT+2:00

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.10.45:8082/eureka/

